### ISSUE TITLE
Documentation landing page

### ISSUE THREAD

**Issue by ValorNaram** [trufi-association/mapping-documentation-french#11]
Open https://github.com/trufi-association/mapping-documentation-french/blob/master/docs/index.md **or** clone the repo to your computer in order to edit the file.

**Comment by AKEAmazan** [comment]
Translation done

**Comment by ValorNaram** [comment]
You are very active :)

**Comment by ValorNaram** [comment]
but please assign yourself to the issue next time you do one by heading over to the "Assignees" section on the right hand site (clicking on the little setting icon) and then selecting your name so others know that you are working on that.

This prevents conflicts (no worries, no ones occurred yet)

**Comment by AKEAmazan** [comment]
ok, thank you for the tips
