### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by ValorNaram** [trufi-association/mapping-documentation-french#12]
Please answer to this issue with the French version of

    <Name> (<Organisation hyperlink>) translated the page into french. Original work by Sören Reinecke (Trufi Association)

    Anonymous translated the page into french. Original work by Sören Reinecke (Trufi Association)

I will apply this notice to any pages translated with the name and optionally a hyperlink to the organisation/initiative/community the translator works for/is in/belongs to. I add this after the translator has uploaded their work because then I can see who translated it.

An attribution on a page looks like the lightblue box on https://mapping-bus-routes.readthedocs.io/fr/master/adding-bus-stops/

**Comment by ldenium** [comment]
<TCHAMIE Léleng Denis> (<https://openstreetmap.tg/>) a traduit la page en français. Oeuvre originale de Sören Reinecke (Association Trufi)

**Comment by ValorNaram** [comment]
**Thanks, closing this**
