### ISSUE TITLE
Adding bus stops

### ISSUE THREAD

**Issue by ValorNaram** [trufi-association/mapping-documentation-french#2]
Open https://github.com/trufi-association/mapping-documentation-french/blob/master/docs/adding-bus-stops/index.md **or** clone the repo to your computer in order to edit the file.

**Comment by AKEAmazan** [comment]
Done

**Comment by ValorNaram** [comment]
Please check, if the attribution is correct at https://mapping-bus-routes.readthedocs.io/fr/master/adding-bus-stops/

**Comment by AKEAmazan** [comment]
Done
